name: "Publish latest server docker image automatically"
# todo: expand the yaml to deal with multi release version 
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  build_latest:
    runs-on: ubuntu-latest
    env:
      repository_url: apache/incubator-hugegraph
      branch: master
      image_url: hugegraph/hugegraph:latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Checkout latest
      uses: actions/checkout@v3
      with:
        repository: ${{ env.repository_url }}
        ref: ${{ env.branch }}
        fetch-depth: 2

    - name: Get current SHA
      run: |
        current_sha=$(git rev-parse HEAD)
        echo "current_sha=$current_sha" >> $GITHUB_ENV

    - name: Get last SHA
      run: |
        is_update='true'
        last_sha=${{vars.LATEST_SHA}}
        if [[ "$current_sha" == "$last_sha" ]]; then
          is_update='false'
        fi
        echo "is_update=$is_update" >> $GITHUB_ENV

    - name: Build X86 Image
      if: env.is_update == 'true'
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: ${{ env.image_url }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test X86 Image
      if: env.is_update == 'true'
      run: |
        docker images
        docker run -itd --name=graph -p 18080:8080 $image_url
        sleep 20s
        curl 0.0.0.0:18080 || exit
        docker ps -a
        sleep 20s
        curl 0.0.0.0:18080 || exit
        docker ps -a

    - name: Build ARM & Push all
      if: env.is_update == 'true'
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.image_url }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Updata last SHA
      env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          OWNER: aroundabout
          REPO: action_demo
      run: |
        var_name='LATEST_SHA'
        last_sha=${{vars.LATEST_SHA}}
        if [[ "$current_sha" != "$last_sha" ]]; then
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
          https://api.github.com/repos/$OWNER/$REPO/actions/variables/$var_name \
          -d '{"name":"'"$var_name"'","value":"'"${{ env.current_sha }}"'"}'
        fi
