name: "Publish server image(latest)"
# todo: expand the yaml to deal with multi release version 
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  build_latest:
    runs-on: ubuntu-latest
    env:
      repository_url: apache/hugegraph
      branch: master
      image_url: hugegraph/hugegraph:latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Checkout latest
      uses: actions/checkout@v3
      with:
        repository: ${{ env.repository_url }}
        ref: ${{ env.branch }}
        fetch-depth: 2

    - name: Get current commit-hash
      run: |
        current_commit_hash=$(git rev-parse HEAD)
        echo "current_commit_hash=$current_commit_hash" >> $GITHUB_ENV

    - name: Get last commit-hash
      run: |
        last_commit_hash=${{vars.LAST_COMMIT_HASH}}
        need_update='false'
        if [[ "$current_commit_hash" != "$last_commit_hash" ]]; then
          need_update='true'
        fi
        echo "need_update=$need_update" >> $GITHUB_ENV

        # To do: if github provide support for exit gracefully, replace if statements with exit.
        # until 2023, there is no official support from github to use "exit gracefully"
        # If exit 0, the left steps still continue. If exit 1, the action will fail.
        # https://github.com/actions/runner/issues/662#issuecomment-1506792423

    - name: Build X86 Image
      if: env.need_update == 'true'
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: ${{ env.image_url }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test X86 Image
      if: env.need_update == 'true'
      run: |
        docker images
        docker run -itd --name=graph -p 18080:8080 $image_url
        sleep 20s
        curl 0.0.0.0:18080 || exit
        docker ps -a
        sleep 20s
        curl 0.0.0.0:18080 || exit
        docker ps -a

    - name: Build ARM & Push all
      if: env.need_update == 'true'
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ env.image_url }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Updata last commit-hash
      if: env.need_update == 'true'
      env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          OWNER: hugegraph
          REPO: hugegraph-actions
      run: |
        var_name='LAST_COMMIT_HASH'
        last_commit_hash=${{vars.LAST_COMMIT_HASH}}
        curl -L \
        -X PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
        https://api.github.com/repos/$OWNER/$REPO/actions/variables/$var_name \
        -d '{"name":"'"$var_name"'","value":"'"$current_commit_hash"'"}'
